//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PvP_SoS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GenelEntities : DbContext
    {
        public GenelEntities()
            : base("name=GenelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SoS_Kullanici> SoS_Kullanici { get; set; }
        public virtual DbSet<SoS_Oyun_İci> SoS_Oyun_İci { get; set; }
        public virtual DbSet<SoS_Oyun_Kabul> SoS_Oyun_Kabul { get; set; }
        public virtual DbSet<SoS_Sohbet> SoS_Sohbet { get; set; }
    }
}
