//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PvP_SoS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoS_Oyun_İci
    {
        public int OyunId { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<int> Kazanan { get; set; }
        public Nullable<int> HamleSayisi { get; set; }
        public Nullable<int> Degisenİndis { get; set; }
        public string İndisDegeri { get; set; }
        public bool Bittimi { get; set; }
        public int Ben { get; set; }
        public int O { get; set; }
    }
}
