//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PvP_SoS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoS_Sohbet
    {
        public int Id { get; set; }
        public int Sohbet_id { get; set; }
        public int Kimden { get; set; }
        public int Kime { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Mesaj { get; set; }
        public int Bittimi { get; set; }
    }
}
